### ISSUE TITLE
reqpoll test fails (bad test logic) sometimes

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#1057]
See in the cloud:

```
Failures:

  * Assertion Failed (Not writable with message pending)
  File: ../tests/reqpoll.c
  Line: 107
  Test: isready(fd) == 0
```

Reading the test code, we try to stuff the queue by calling sendmsg a bunch.  Unfortunately, this fails to consider an important element in the REQ protocol, which is that sending a message may cancel other messages, even before it gets to the wire.  This means that the attempt to fill the pipe might be bogus, as the underlying pipe reader might not have picked up the message(s) yet.

The only way to forcibly hit this is going to be to inject sufficient delay to ensure that the pipe reader is stuck.

Note also that the pipe logic needs to allow for one message to be handled on the other side, by it's reader, and and possibly one in transit.

We might want to look at building a mock transport, which is what we did for mangos to facilitate testing these edge cases.
