### ISSUE TITLE
Occasional orphaned pipe or endpoint?

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#28]
When running the ipc test in a tight loop, we will occasionally see failures like this:

```
Failures:

  * Listen and accept (Assertion Failed)
  File: /home/parallels/Projects/nng/tests/trantest.h
  Line: 92
  Test: nng_listen(tt->repsock, tt->addr, &ep, NNG_FLAG_SYNCH) == 0
```

(Sometimes it can be a dial failure too.)  I'm fairly certain that what is happening here is that the /tmp/nng_ipc_test pipe isn't getting cleaned up (and I think I've seen a similar problem with TCP), resulting in EADDRINUSE.  After the program exits, the thing is gone.

It takes *many* runs to trigger this failure.  Usually several hundred at least.  This is on an Ubuntu vm, but I think I've seen failures in MacOS too.

I added a slight delay in my loop, and that didn't fix the problem (but it took a lot longer to hit, of course.)  (I was hoping that maybe this was an operating system level race, where close() didn't free the resource entirely... no such luck.)

More work to track this down is needed.
